try {  
  const a = 1;
  const b=0;  
  const c = a / b;    
} catch (err) {  
  console.log(err);
} 